feat: improve EdgeScan script error handling for ES_API_TOKEN and ES_ASSET_ID validation; fix syntax errors

diff --git a/build-pipeline/core/monorepo-edgescan-stage.yml b/build-pipeline/core/monorepo-edgescan-stage.yml
--- a/build-pipeline/core/monorepo-edgescan-stage.yml
+++ b/build-pipeline/core/monorepo-edgescan-stage.yml
@@ -28,20 +28,24 @@ stages:
         script: |
           set -euo pipefail
 
-          if [ -z "${ES_API_TOKEN}" ] || [ -z "$(ES_ASSET_ID)" ]; then
-            echo "Error: Error: ES_API_TOKEN and ES_ASSET_ID must be set in the variable group."
+          if [ -z "$ES_API_TOKEN" ] then
+            echo "Error: Error: ES_API_TOKEN must be set in the variable group."
+            exit 1
+          fi
+
+          if [ -z "${{ parameters.esAssetId }}" ]; then
+            echo "Error: ES_ASSET_ID_DEV must be set in the variable group."
             exit 1
           fi
 
           docker pull edgescan/cicd-integration:latest
           
-          echo "Triggering EdgeScan for Asset ID: ${{parameters.esAssetId}}"
+          echo "Triggering EdgeScan for Asset ID: ${{ parameters.esAssetId }}"
           
           docker run --rm \
-            -e ES_API_TOKEN=$(ES_API_TOKEN) \
-            -e ES_ASSET_ID=${{parameters.esAssetId}} \
+            -e ES_API_TOKEN=$ES_API_TOKEN \
+            -e ES_ASSET_ID=${{ parameters.esAssetId }} \
             -e MAX_RISK_THRESHOLD=3 \
             edgescan/cicd-integration:latest --wait --color
       env:
         ES_API_TOKEN: $(ES_API_TOKEN)
-        ES_ASSET_ID: $(ES_ASSET_ID)
